In [1]:

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv('insurance_pre.csv')
dataset.head()

   age     sex     bmi  children smoker      charges
0   19  female  27.900         0    yes  16884.92400
1   18    male  33.770         1     no   1725.55230
2   28    male  33.000         3     no   4449.46200
3   33    male  22.705         0     no  21984.47061
4   32    male  28.880         0     no   3866.85520

In [3]:
dataset = pd.get_dummies(dataset,dtype=int, drop_first=True)
dataset.head()

   age     bmi  children      charges  sex_male  smoker_yes
0   19  27.900         0  16884.92400         0           1
1   18  33.770         1   1725.55230         1           0
2   28  33.000         3   4449.46200         1           0
3   33  22.705         0  21984.47061         1           0
4   32  28.880         0   3866.85520         1           0

In [4]:
indep = dataset[['age', 'bmi', 'children', 'sex_male', 'smoker_yes']]
dep = dataset['charges']

In [ ]:
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVR

param_grid = {'kernel': ['rbf', 'poly', 'sigmoid', 'linear'],
              'C': [10, 100, 1000, 2000, 3000],
               'gamma': ['auto', 'scale']}
grid = GridSearchCV(SVR(), param_grid, refit=True, verbose=3, n_jobs=-1)
grid.fit(indep,dep)

Fitting 5 folds for each of 40 candidates, totalling 200 fits

In [ ]:
print('Best parameters:', grid.best_params_)
print('Best cross-validation R² score:', grid.best_score_)
results = pd.DataFrame(grid.cv_results_)
results.head()

In [ ]:
age_input = float(input('Age: '))
bmi_input = float(input('BMI: '))
children_input = float(input('Children: '))
sex_male_input = int(input('Sex Male (0 or 1): '))
smoker_yes_input = int(input('Smoker Yes (0 or 1): '))


new_person = pd.DataFrame([[age_input, bmi_input, children_input, sex_male_input, smoker_yes_input]],
    columns=['age', 'bmi', 'children', 'sex_male', 'smoker_yes'])
new_person_scaled = sc.transform(new_person)
future_prediction = grid.predict(new_person_scaled)
print(f'Future_Prediction = {future_prediction[0]:.2f}')